#!/bin/bash
#This script is executed every time your instance is spawned.
LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
curl -Lo /home/b33nan/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf /home/b33nan/lazygit.tar.gz -C /home/b33nan/
sudo install /home/b33nan/lazygit /usr/local/bin
rm -rf /home/b33nan/lazygit*
cp /home/b33nan/my_data/.configs/.vimrc /home/b33nan/.vimrc
cp /home/b33nan/my_data/.configs/.bashrc /home/b33nan/.bashrc
git config --global user.email "keekunz@gmail.com"
git config --global user.name "Keenan Kunzelman"



